// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yelcasrxgrbzmpdqthnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllbGNhc3J4Z3Jiem1wZHF0aG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NjA5NjIsImV4cCI6MjA2NTQzNjk2Mn0.cgiCb0kNngzHYKyQrIV0r_O3ba1qIY85xEGgNsIi9Bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);